### ISSUE TITLE
i want to add my code on how to find a prime number

### ISSUE THREAD

**Issue by Poonji** [kinston18/CPP-DSA#5]

**Comment by varsha-kss** [comment]
i can resolve this issue

**Comment by AkashB2208** [comment]
@kinston18 pls assign it to me

**Comment by sangalgovind** [comment]
@Poonji ### assign it to me

**Comment by sangalgovind** [comment]
i can resolve this issue

**Comment by ShreyaShukla03** [comment]
hello sir, Can you assign this to me?

**Comment by Arika008** [comment]
@kinston18 Please check my PR #11 and merge my request

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?
